### ISSUE TITLE
Expose metrics from calico node

### ISSUE THREAD

**Issue by captncraig** [kontena/pharos-cluster#1031]
I would like to scrape metrics from the calico-node pods. Since calico-node runs on host network, probably needs to have config to enable it.

I propose config: `network.calico.enable_metrics` to enable it. Things that need to be changed:

- [Enable in felix](https://docs.projectcalico.org/v3.5/reference/felix/configuration) by setting FELIX_PROMETHEUSMETRICSENABLED to true.
- Optionally set FELIX_PROMETHEUSMETRICSPORT from another config item (or stick with default 9091 for simplicity)
- Add port to container ports.
- Add a headless service that selects those pods (I could do that myself if pharos doesn't).

**Comment by jnummelin** [comment]
Is there any reason why we should not enable metrics always?

**Comment by captncraig** [comment]
I'd be ok with that. My only concern was that calico-node uses host networking, so grabbing another port has more consequences if you are not expecting it. It's unlikely to conflict with other things though.

**Comment by jnummelin** [comment]
Yeah, port conflicts are painfull. So maybe enable the metrics always and make the port configurable with `network.calico.metrics_port` which defaults to `9091`.

**Comment by captncraig** [comment]
That seems pretty reasonable.
