### ISSUE TITLE
Pharos worker up

### ISSUE THREAD

**Issue by jakolehm** [kontena/pharos-cluster#1086]
**What would you like to be added**:

`pharos worker up [--config] [--token] [--maybe-others]` sub-command that executes all the needed worker phases locally and joins a worker to the cluster.

**Why is this needed**:

Would make autoscaling etc use cases easier .

**Comment by jakolehm** [comment]
#1044 should make this easier.

**Comment by kke** [comment]
There probably needs to be some way for `pharos up` to be aware of the nodes added in this fashion?

**Comment by jakolehm** [comment]
> There probably needs to be some way for `pharos up` (and `reset` etc) to be aware of the nodes added in this fashion? What about ssh keys?

Everything is done out-of-band so `pharos up` does not need to know anything more than it knows already. It's users responsibility to create the automation for these hosts.
