### ISSUE TITLE
pharos-cluster up silently ignores multiple resource definitions in single YAML file

### ISSUE THREAD

**Issue by pre** [kontena/pharos-cluster#1167]
Assume you have a pharos-addon `lolcat` with `lolcat/resources/10-configmap.yml`.

If `10-configmap.yml` contains multiple resource definitions concatenated with `---` into a single file, `pharos-cluster up` will only apply the top-most resource definition in this YAML file. There is no warning or a message that the rest were ignored. 

This causes a surprise when part of your addon wasn't deployed even though `pharos-cluster up` completed succesfully without warnings.

Problem goes away by splitting the concatenated yaml file into multiple yaml files.

**Environment**:
- Pharos version (use `pharos --version`): 2.1.5

**Comment by kke** [comment]
Odd.

```
# lib/pharos/kube/stack.rb
# frozen_string_literal: true

require 'k8s-client'

module Pharos
  module Kube
    class Stack < K8s::Stack
      # custom labels
      LABEL = 'pharos.kontena.io/stack'
      CHECKSUM_ANNOTATION = 'pharos.kontena.io/stack-checksum'

      # Load stack with resources from path containing erb-templated YAML files
      #
      # @param path [String]
      # @param name [String]
      # @param vars [Hash]
      def self.load(name, path, **vars)
        path = Pathname.new(path).freeze
        files = Pathname.glob(path.join('*.{yml,yaml,yml.erb,yaml.erb}')).sort_by(&:to_s)
        resources = files.flat_map do |file|

          ############################
          Pharos::YamlFile.new(file).load_stream(name: name, **vars) do |doc|
            K8s::Resource.new(doc)
          end
          ############################

        end.select do |r|
          # Take in only resources that are valid kube resources
          r.kind && r.apiVersion
        end

        new(name, resources)
      end
    end
  end
end
```

This should handle multi-doc yamls just fine.

**Comment by kke** [comment]
This came in #1017 which was added in 2.2.0
