### ISSUE TITLE
Icebox check on pharos up

### ISSUE THREAD

**Issue by kke** [kontena/pharos-cluster#1173]
`pharos up`  should probably check during validation if the cluster has been iceboxed and warn / abort / act accordingly.

`reset` may need to know it too?

**Comment by kke** [comment]
@jnummelin is there some command line spell that can be run on master to figure out if it has been iceboxed?

**Comment by jnummelin** [comment]
`count(shceduler pods) == count(controller manager pods) == count(nodes)`

**Comment by kke** [comment]
```
vagrant@host-02:~$ count(shceduler pods) == count(controller manager pods) == count(nodes)
-bash: syntax error near unexpected token `shceduler'
```

:)

**Comment by kke** [comment]
so kubectl should still work on master?

**Comment by jnummelin** [comment]
yes, the API is still up-and-running

**Comment by kke** [comment]
or `== count(master nodes)`?

**Comment by jnummelin** [comment]
> or == count(master nodes)?

That's what it reads on the comment. :) (Yes, I've edited it after the initial post)
