### ISSUE TITLE
CoreDNS crash on CentOS 7.4

### ISSUE THREAD

**Issue by rlondner** [kontena/pharos-cluster#1178]
**What would you like to be added**:
Full support for CoreDNS deployment on CentOS 7.4
**Why is this needed**:
Without a proper fix, Kontena Lens is inaccessible. A workaround is to run the following command once the Pharos cluster has been deployed, but it's a bit inconvenient:

`kubectl -n kube-system get deployment coredns -o yaml | sed 's/allowPrivilegeEscalation: false/allowPrivilegeEscalation: true/g' | kubectl apply -f -`

**Example cluster.yml**:

**Comment by jakolehm** [comment]
CentOS 7.5 should work (use `yum` to update).
