### ISSUE TITLE
Upgrade cert-manager to v0.7.2

### ISSUE THREAD

**Issue by olanystrom** [kontena/pharos-cluster#1316]
I would like to have cert-manager updated to v0.7.2 (curent stable) or v0.6.2 (stable in 0.6-release)
I need the DNS01 provider DigitalOcean that was added in 0.6.0-release

Action Required (from 0.7.0 release)
The Helm chart rbac.create option has moved to be global.rbac.create.
Users of the Helm chart will need to update their install overrides to use
the new format.

The Helm chart has now moved to be hosted on charts.jetstack.io, and
exposed via the Helm Hub. This allows us to make
and test changes to the Helm chart more easily, and better manage versioning.

**Comment by jnummelin** [comment]
Looking at the [release notes](https://github.com/jetstack/cert-manager/releases) I don't see anything requiring any migration logic on Pharos. So it should be enough to make the images properly synced and bumping the add-on version.
