### ISSUE TITLE
Is Weave Network configured to encrypt traffic between masters/nodes?

### ISSUE THREAD

**Issue by chrismessiah** [kontena/pharos-cluster#1357]
**What would you like to be added**:
Hi! I was looking in the docs (https://pharos.sh/docs/networking/#weave) and noted that a shared secret is either supplied by config or generated for Weave. Is this secret used to encrypt traffic between nodes and masters? If not, what is the secret used for and does Pharos provide/support encryption of network traffic?

**Why is this needed**:
The `password`-section assumes knowledge of or familiarity with Weave. Since I haven't used Weave before I would love some clarification.

Thanks!

**Comment by jakolehm** [comment]
Pharos generates Weave secret automatically during install. This secret is used for host-to-host encryption (IPSec) and also for Weave control-plane authentication. Network encryption can be disabled for given trusted-subnets.

**Comment by chrismessiah** [comment]
Right! So if pods located on different nodes communicate via http (non-ssl/tls) the traffic will actually be encrypted by the underlying network layers?

**Comment by jnummelin** [comment]
Yes, that's correct

**Comment by chrismessiah** [comment]
Nice. Closing this as my question has been answered. It would be nice to add a sentence or two clarifying this in the docs. 

Keep up the good work!
