### ISSUE TITLE
CentOS 7.7 support

### ISSUE THREAD

**Issue by voneiden** [kontena/pharos-cluster#1495]
[System requirements](https://pharos.sh/docs/requirements.html#supported-machines--operating-systems) page indicates that CentOS 7.4-7.5 are supported. Issue #745 indicates that 7.6 is supported. How about 7.7?

**Comment by HristoA** [comment]
Hi @voneiden 
CentOS7 is already supported on Pharos 2.4.8
https://github.com/kontena/pharos-cluster/pull/1487
Have a good day :)
