### ISSUE TITLE
Enable secrets encryption

### ISSUE THREAD

**Issue by jakolehm** [kontena/pharos-cluster#177]
https://kubernetes.io/docs/tasks/administer-cluster/encrypt-data/

**Comment by jnummelin** [comment]
Should we make it encrypted by default? If we do, should we at this point also make automatic move from un-uncrypted secrets, a.k.a migration?

How about the key(s)? How should we take those in? Having them in `cluster.yml` might leak them easily. I see two options:
a) provide them as options/envs to  up command
b) generate them on the fly and dump out after cluster setup with a note that these are supposed to be kept somewhere safe. :)

**Comment by jakolehm** [comment]
Encryption should be enabled by default (is there _any_ reason not to encrypt?).

Option b) sounds good to me.

**Comment by jnummelin** [comment]
> is there any reason not to encrypt?

Not really, just wanted to double check we **don't** want to have that configurable :)

**Comment by jakolehm** [comment]
> Not really, just wanted to double check we don't want to have that configurable :)

I might change my mind after I see the first implementation 😄 

![maybe](https://media.giphy.com/media/DfdbTJZx6Yjra/giphy.gif)
