### ISSUE TITLE
How to reach kubernetes api and dashboard

### ISSUE THREAD

**Issue by jeroenpeeters** [kontena/pharos-cluster#196]
Hi, I've sucessfully set up a cluster using pharos. However, I do not see how to actually use it. Where do I connect? I've also started the kubernetes dashboard, but i don't see any exposed ports. I'm unable to find documentation on this topic. Can you give me some pointers?

**Comment by jeroenpeeters** [comment]
@jakolehm thanks, that works indeed. I have to add that I'm not an experienced kubernetes user. I do have a Docker Swarm background though and I'm trying pharos to see if it will give me a smooth upgrade path to kubernetes.
I've deployed with the 
     kubernetes-dashboard:
         enabled: true
option. How do I access the dashboard? Do I manually need to expose it somehow?

**Comment by jakolehm** [comment]
```
$ kubectl proxy
```
and then open browser at http://localhost:8001/ui .

You will need a token for accessing the dashboard, see https://github.com/kubernetes/dashboard/wiki/Creating-sample-user .

Pharos probably should add a service account automatically if dashboard addon is enabled.

**Comment by jakolehm** [comment]
Things will get better, see #210 .
