### ISSUE TITLE
5-pharos-*.conf dropins are confusing

### ISSUE THREAD

**Issue by jakolehm** [kontena/pharos-cluster#242]
See: https://github.com/kontena/pharos-cluster/pull/222#discussion_r181701530

**Comment by SpComb** [comment]
> BTW: calling these `5-pharos-*.conf` is super confusing, because that implies that they would sort before the `10-kubeadm.conf`. Instead, they actually sort after, so they should really be called something like `50-pharos-*.conf`:

```
$ ls -l /etc/systemd/system/kubelet.service.d/
total 8
-rw-r--r-- 1 root root 937 Mar 27 15:50 10-kubeadm.conf
-rw-r--r-- 1 root root 243 Apr 13 14:09 5-pharos.conf
```

> And renaming these to `05-pharos.conf` would probably break it, they need to come after the `10-kubeadm.conf`, because they override the `ExecStart=...` in this case.

**Comment by SpComb** [comment]
> Calling these `5-pharos-*.conf` is super confusing, because that implies that they would sort before the `10-kubeadm.conf`. Instead, they actually sort after, so they should really be called something like `50-pharos-*.conf`:

```
$ ls -l /etc/systemd/system/kubelet.service.d/
total 8
-rw-r--r-- 1 root root 937 Mar 27 15:50 10-kubeadm.conf
-rw-r--r-- 1 root root 243 Apr 13 14:09 5-pharos.conf
```

> And renaming these to `05-pharos.conf` would probably break it, they need to come after the `10-kubeadm.conf`, because they override the `ExecStart=...` in this case.

**Comment by SpComb** [comment]
This is now `11-pharos.conf`: https://github.com/kontena/pharos-cluster/blob/981e2c4fbef44e622af39bce2a305b93e3af590f/lib/pharos/phases/configure_kubelet.rb#L17
