### ISSUE TITLE
Host role change does not really work

### ISSUE THREAD

**Issue by jnummelin** [kontena/pharos-cluster#305]
With the master re-size coming in from #293 the change or host roles does not really work. There's two issues:

1. Etcd gets left behind on host changed from master -> worker
```
etcd-jussi-worker-1                         0/1       CrashLoopBackOff   6          23m       178.62.212.223   jussi-worker-1
```

It's in `CrashLoopBackOff` since that member has been "evicted" from etcd cluster but still the static manifest for is remains in `/etc/kubernetes/manifests/pharos-proxy.yaml`

2. Apiserver won't start on host changed from worker -> master

```
root@jussi-worker-2:~# ./crictl logs b76f848f5afbb
Flag --admission-control has been deprecated, Use --enable-admission-plugins or --disable-admission-plugins instead. Will be removed in a future version.
Flag --insecure-port has been deprecated, This flag will be removed in a future version.
I0425 07:13:21.059001       1 server.go:135] Version: v1.10.1
I0425 07:13:21.059166       1 server.go:717] external host was not specified, using 188.166.36.138
failed to create listener: failed to listen on 0.0.0.0:6443: listen tcp 0.0.0.0:6443: bind: address already in use
```

That's because the workers kubelet-proxy is still running and hogging the port.

---

First step would be to disable the possibility to do role changes in validation phase.

Second step would be to run some sort of "reset" and remove all things not needed for the role.

**Comment by SpComb** [comment]
Ref #309, I suppose this still remains open as a feature request for resetting the existing node configuration when changing roles?

**Comment by jnummelin** [comment]
I think we can close this and open a new feature request on node role changes if that seems to be needed.
