### ISSUE TITLE
Pharos::Masters::SetupMaster uses wrong Kubeadm class

### ISSUE THREAD

**Issue by nevalla** [kontena/pharos-cluster#397]
Pharos::Masters::SetupMaster uses wrong class to initialize kubeadm config generator object:
```
module Pharos
  module Phases
    class SetupMaster < Pharos::Phase
      title "Setup master configuration files"

      def kubeadm
        Pharos::Kubeadm.new(@config, @host)
      end
```
 it should be `Pharos::Kubeadm::ConfigGenerator.new(@config, @host)` instead.

Getting this error now:
```
[Setup master configuration files @ 35.x.x.x] ArgumentError: wrong number of arguments (given 2, expected 0)
```

**Comment by SpComb** [comment]
This only happens if external `etcd`, `audit`, `authentication.token_webook` or `cloud` is configured...
