### ISSUE TITLE
Api certs are not regenerated if api.endpoint changes

### ISSUE THREAD

**Issue by jakolehm** [kontena/pharos-cluster#434]

**Comment by SpComb** [comment]
Confirm that `rm /etc/kubernetes/pki/apiserver.crt && kubeadm alpha phase certs apiserver --config ...` with the new config containing the updated `apiServerCertSANs` list is enough to update the cert.

Note that removing the cert and running `kubeadm alpha phase controlplane all` leaves the apiserver in a broken state (`error: unable to load server certificate: open /etc/kubernetes/pki/apiserver.crt: no such file or directory`).
