### ISSUE TITLE
Docker0 bridge can conflict with service/pod cidrs

### ISSUE THREAD

**Issue by jakolehm** [kontena/pharos-cluster#439]
This is pretty hard to spot (at least with calico)... everything else works but http liveness/readiness probes will fail.

**Comment by captncraig** [comment]
Side note, avoiding this does not appear to have solved my issues with liveness probes I was experiencing with calico. Will continue investigating minimal repro tomorrow.

**Comment by SpComb** [comment]
> Side note, avoiding this does not appear to have solved my issues with liveness probes I was experiencing with calico. Will continue investigating minimal repro tomorrow.

Based on the `ip addr` output that I saw, this is presumably a separate issue with calico `ipip_mode: Never`... you can try with `ipip_mode: CrossSubnet` instead, which should setup the `tunl0` interface on the host with a local source address within the pod cidr, but still use direct routing assuming that your hosts are on the same L2 subnet.

If that fixes the issue with liveness probes, then it's a separate issue from this IP conflict.

**Comment by SpComb** [comment]
Validating this is actually non-trivial, because after the initial install we need to ignore all of the actual pod network routes. That makes it network-provider-specific.
