### ISSUE TITLE
Pharos does not honor system ssh config

### ISSUE THREAD

**Issue by captncraig** [kontena/pharos-cluster#443]
I have set `~/.ssh/config` up with the following:

```
Host *kubecl*
    User svc_kubernetes
    IdentityFile ~/.ssh/kube.key
```

and my pharos config contains hosts like:

```
  - address: "devkubecl-node01.mydomain"
    private_address: "10.0.43.8"
    role: worker
```

Pharos does not seem to get the user/key from the ssh config:

`ubuntu@devkubecl-node01.mydomain's password:`

Fully specifying username and ssh key still works. Just specifying user or key alone are also not sufficient.

**Comment by captncraig** [comment]
The other context I hope to deploy from is teamcity. In that environment, the key will be pre-loaded into ssh-agent by the build runner, but the username will still come from the local ~/.ssh/config I think.

**Comment by kke** [comment]
I have a hunch that the username is always read from `cluster.yml` even if ssh config defines one.

**Comment by SpComb** [comment]
The `Pharos::Configuration::Host's `user` defaults to `ubuntu`... that's a bug at this point: https://github.com/kontena/pharos-cluster/blob/5c90b3ae3f6b8837f6de6b289df1dd85ff27e5a2/lib/pharos/configuration/host.rb#L17
