### ISSUE TITLE
Kubernetes v1.10.5

### ISSUE THREAD

**Issue by jakolehm** [kontena/pharos-cluster#463]
https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.10.md#changelog-since-v1104

Tested 1.10.5 but it seems to drop master taints.. needs more investigation.

**Comment by SpComb** [comment]
> Tested 1.10.5 but it seems to drop master taints.. needs more investigation.

Maybe this is #470?

**Comment by SpComb** [comment]
Upgrading to 1.10.5 without `labels` or `taints` set, the master taint is still there:

```
root@terom-pharos-master:~# kubectl get nodes/terom-pharos-master -o json | jq .spec
{
  "externalID": "terom-pharos-master",
  "podCIDR": "10.32.0.0/24",
  "taints": [
    {
      "effect": "NoSchedule",
      "key": "node-role.kubernetes.io/master"
    }
  ]
}
root@terom-pharos-master:~# kubectl version --short
Client Version: v1.10.5
Server Version: v1.10.5
```
