### ISSUE TITLE
Ubuntu xenial no longer provides docker.io 1.13.1

### ISSUE THREAD

**Issue by wolfedale** [kontena/pharos-cluster#476]
Pharos is not working anymore as it is using docker package which is missing from the repository.

The error is: `Version '1.13.1-0ubuntu1~16.04.2' for 'docker.io' was not found`

Version of this package is hardcoded at the `ubuntu_xebial.rb`:

```
34       def configure_container_runtime¬
 35         if docker?¬
 36           exec_script(¬
 37             'configure-docker.sh',¬
 38             DOCKER_PACKAGE: 'docker.io',¬
 39             DOCKER_VERSION: "#{DOCKER_VERSION}-0ubuntu1~16.04.2"¬
 40           )
```

**Comment by SpComb** [comment]
Looks like `xenial-updates` bumped `docker.io` to 17.03.2

```
docker.io:
  Installed: 1.13.1-0ubuntu1~16.04.2
  Candidate: 17.03.2-0ubuntu2~16.04.1
  Version table:
     17.03.2-0ubuntu2~16.04.1 500
        500 http://mirrors.digitalocean.com/ubuntu xenial-updates/universe amd64 Packages
 *** 1.13.1-0ubuntu1~16.04.2 100
        100 /var/lib/dpkg/status
     1.10.3-0ubuntu6 500
        500 http://mirrors.digitalocean.com/ubuntu xenial/universe amd64 Packages
```

**Comment by SpComb** [comment]
Fixing this is presumably going to mean a 1.2.2 release bumping xenial hosts to `docker.io` 17.03.

**Comment by SpComb** [comment]
https://github.com/kontena/pharos-cluster/releases/tag/v1.2.2-rc.1 is now out for testing, this will be 1.2.2 once the new Docker version checks out.

OS X packages available shortly: https://travis-ci.org/kontena/pharos-cluster/builds/405390419

**Comment by kashifusmani** [comment]
Hello, I am seeing a similar error, not sure if its related. Here are the details.

Pharos version: v1.2.3 (Mac OS)
OS: Ubuntu 16.04 

Error message while running `./pharos-cluster-darwin-amd64 up -c cluster.yml`: 
```
+ apt-get install -y docker.io=17.03.2-0ubuntu2~16.04.1
Reading package lists...
Building dependency tree...
Reading state information...
E: Version '17.03.2-0ubuntu2~16.04.1' for 'docker.io' was not found
```

Is there a way to fix it manually by changing the config somewhere?

**Comment by jakolehm** [comment]
@kashifusmani v1.2.3 should work, could you double check the `pharos-cluster` version (`pharos-cluster -v`)?

**Comment by jakolehm** [comment]
@kashifusmani maybe your ubuntu image uses repositories that does not have the latest docker.io package? It should be in `xenial-updates`, see: https://packages.ubuntu.com/xenial-updates/docker.io .

**Comment by kashifusmani** [comment]
@jakolehm I think you are correct. But I expected pharos to do that for me as well. Does it not add the  repo if already not added?

**Comment by kashifusmani** [comment]
@jakolehm Version are

```pharos-cluster 1.2.2
pharos-cluster 1.2.3```

**Comment by jakolehm** [comment]
@kashifusmani v1.2.2 switched to the newer docker.io package (older is removed from most repos). See https://github.com/kontena/pharos-cluster/releases/tag/v1.2.2
