### ISSUE TITLE
pharos-telemetry Pods not ready

### ISSUE THREAD

**Issue by AMO-MTSY** [kontena/pharos-cluster#584]
Hi,
Got these pods deployed on a cluster
kubectl get pods --namespace kube-system
pharos-telemetry-1535734800-xfklq      0/1       Completed   0          2h
pharos-telemetry-1535738400-f48lh      0/1       Completed   0          1h
pharos-telemetry-1535742000-8l8jk      0/1       Completed   0          11m

I would like to ask: what is the purpose of pharos-telemetry? and why they are not ready?

**Comment by jakolehm** [comment]
Those pods are coming from the telemetry CronJob. Completed means that it has been executed successfully. For more info about Pharos telemetry, see here: https://www.pharos.sh/docs/configuration.html#telemetry .
