### ISSUE TITLE
pharos-cluster version 1.3.0 fails with Centos/7 

### ISSUE THREAD

**Issue by jeremy-moore** [kontena/pharos-cluster#585]
Running example Vagrant Centos/7 gives the following (same as actual servers):
  
pharos-cluster up
==> KONTENA PHAROS v1.3.0 (Kubernetes v1.11.1)
==> Reading instructions ...
==> Sharpening tools ...
==> Gather host facts @ 192.168.110.100 192.168.110.101 192.168.110.102
    [192.168.110.102] Checking sudo access ...
    [192.168.110.101] Checking sudo access ...
    [192.168.110.100] Checking sudo access ...
    [192.168.110.100] Gathering host facts ...
    [192.168.110.101] Gathering host facts ...
    [192.168.110.102] Gathering host facts ...
    [host-00] got error (Pharos::SSH::RemoteCommand::ExecError): SSH exec failed with code 127: ip route
bash: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
/etc/profile.d/lang.sh: line 32: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
bash: ip: command not found
    [host-00] retrying after 1 seconds ...
    [host-01] got error (Pharos::SSH::RemoteCommand::ExecError): SSH exec failed with code 127: ip route
bash: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
/etc/profile.d/lang.sh: line 32: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
bash: ip: command not found
    [host-01] retrying after 1 seconds ...
    [host-02] got error (Pharos::SSH::RemoteCommand::ExecError): SSH exec failed with code 127: ip route
bash: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
/etc/profile.d/lang.sh: line 32: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
bash: ip: command not found
    [host-02] retrying after 1 seconds ...
    [192.168.110.100] Checking sudo access ...
    [192.168.110.100] Gathering host facts ...
    [192.168.110.101] Checking sudo access ...
    [192.168.110.101] Gathering host facts ...
    [192.168.110.102] Checking sudo access ...
    [192.168.110.102] Gathering host facts ...
    [host-00] got error (Pharos::SSH::RemoteCommand::ExecError): SSH exec failed with code 127: ip route
bash: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
/etc/profile.d/lang.sh: line 32: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
bash: ip: command not found
    [host-00] retrying after 2 seconds ...
    [host-01] got error (Pharos::SSH::RemoteCommand::ExecError): SSH exec failed with code 127: ip route
bash: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
/etc/profile.d/lang.sh: line 32: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
bash: ip: command not found
    [host-01] retrying after 2 seconds ...
    [host-02] got error (Pharos::SSH::RemoteCommand::ExecError): SSH exec failed with code 127: ip route
bash: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
/etc/profile.d/lang.sh: line 32: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
bash: ip: command not found
    [host-02] retrying after 2 seconds ...
    [192.168.110.100] Checking sudo access ...
    [192.168.110.100] Gathering host facts ...
    [192.168.110.101] Checking sudo access ...
    [192.168.110.101] Gathering host facts ...
    [192.168.110.102] Checking sudo access ...
    [192.168.110.102] Gathering host facts ...
    [host-00] got error (Pharos::SSH::RemoteCommand::ExecError): SSH exec failed with code 127: ip route
bash: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
/etc/profile.d/lang.sh: line 32: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
bash: ip: command not found
    [host-00] retrying after 4 seconds ...
    [host-01] got error (Pharos::SSH::RemoteCommand::ExecError): SSH exec failed with code 127: ip route
bash: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
/etc/profile.d/lang.sh: line 32: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
bash: ip: command not found
...

**Comment by jeremy-moore** [comment]
Works with:
config.vm.box = "ubuntu/bionic64"

**Comment by jnummelin** [comment]
Seems we've made the assumption that Centos has 'ip' binary always available. Pharos CentOS provisioner should ensure that it's available. So definitely a bug.
