### ISSUE TITLE
pharos 1.3.0 ubuntu/bionic - needed to add "universe" repository

### ISSUE THREAD

**Issue by jeremy-moore** [kontena/pharos-cluster#586]
Using Ubuntu 18.04 (bionic) installed from iso on physical machine.
I got the following error:

pharos-cluster up ...
...
    [pharos-worker-1] got error (Pharos::SSH::RemoteCommand::ExecError): SSH exec failed with code 100: configure-docker.sh
...

This was fixed by adding the ubuntu "universe" package repository as follows:

sudo add-apt-repository universe

**Comment by jeremy-moore** [comment]
Maybe similar to #476

**Comment by snoop244** [comment]
Same problem.  I've been pulling my hair out on this.  Install to 18.0.4 was failling as Pharos couldn't find docker.io, though it was installed. Your solution worked.  

Much appreciated.

**Comment by jakolehm** [comment]
Documentation is now updated, see: https://www.pharos.sh/docs/requirements.html#other-requirements
