### ISSUE TITLE
Pharos cluster does not support no_proxy configuration

### ISSUE THREAD

**Issue by ciniajohanjo** [kontena/pharos-cluster#587]
In our environment all outgoing addresses require proxy. There is our own private docker repository, which is not accessible with proxy.

Working solution is to modify on all cluster nodes: 
manually add /etc/system.d/system/docker.d/http-proxy.conf to have NO_PROXY-option 

> Environment="NO_PROXY=repository.server.local" 

Also modifying  /etc/environment to contain following line 

> NO_PROXY="repository.server.local" 

It would be nice to have cluster.yml a option to setup the no-proxy-settings, due we need to verify the settings every time we run 
> pharos up -c cluster.yml 

Affects the pharos 1.3.0 -version

**Comment by Sakhas** [comment]
Pharos still does not add NO_PROXY/no_proxy option configured in cluster.yml to docker http-config (/etc/system.d/system/docker.d/http-proxy.conf) for every node on the cluster. Http_proxy is now correctly set to http-proxy.conf though.

No_proxy still has to be set manually to docker http-proxy.conf after running pharos-cluster up.

**Comment by kke** [comment]
New issue #850
