### ISSUE TITLE
Add support for insecure docker registry

### ISSUE THREAD

**Issue by ciniajohanjo** [kontena/pharos-cluster#588]
Sometimes private docker registries don't use SSL-certificates. 

Could cluster.yml have  option to add list of insecure registries, which would be added to 

/etc/docker/daemon.json 

> {
>   ... 
>  "insecure-registries": ["insecure.server.local"]
>  ... 
> }

**Comment by Timer** [comment]
Any updates on this? Can it be tagged for a milestone, please?

**Comment by jakolehm** [comment]
One option that does not need `insecure-registries`: https://github.com/helm/charts/tree/master/incubator/kube-registry-proxy

Proxy is deployed to every node via DaemonSet and images can be pulled via `localhost:5000/xyz:latest` .

**Comment by Timer** [comment]
This would be a bit odd because deployments will differ from the workflow used via external CI systems/developers.

**Comment by jakolehm** [comment]
> This would be a bit odd because deployments will differ from the workflow used via external CI systems/developers.

I agree, bit odd and is not suitable for every use case.

Maybe we could add something like this to `cluster.yml`:

```yaml
container_runtime:
  insecure_registries:
    - "192.168.1.2:5000"
```

This information would then be injected to docker/cri-o configuration files.
