### ISSUE TITLE
Release the binaries

### ISSUE THREAD

**Issue by swade1987** [kontena/pharos-cluster#595]
If you're releasing the source code does it not make sense to release the binaries as well for easier consumption?

**Comment by jakolehm** [comment]
@jcgruenhage we will add build docs to the readme asap. Meanwhile you can check how we build the binaries from here: https://github.com/kontena/pharos-cluster/blob/master/build/drone/ubuntu_oss.sh . It's also possible to build plain rubygem from the gemspec.

**Comment by jcgruenhage** [comment]
Thanks for the link, that's nearly as good as docs :)
