### ISSUE TITLE
Global kubelet config options should be set to a configmap

### ISSUE THREAD

**Issue by jakolehm** [kontena/pharos-cluster#601]
See https://github.com/kubernetes/kubernetes/pull/63887

**Comment by jnummelin** [comment]
hmm, can we really use that? Wouldn't that mean that every single node gets the same kubelet options? In our case there can be mixture or runtimes, archs etc, so not sure we can/should use this.

I might still not understand the feature fully...

It does also have a beta label: https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/phases/kubelet/dynamic.go#L39

Well, in K8S beta is the new stable though... :D

**Comment by jakolehm** [comment]
Does it really require dynamic kubelet config? https://godoc.org/k8s.io/kubelet/config/v1beta1#KubeletConfiguration

**Comment by jakolehm** [comment]
Fixed in #956
