### ISSUE TITLE
Why Ruby and not Go?

### ISSUE THREAD

**Issue by nikolay** [kontena/pharos-cluster#622]

**Comment by kke** [comment]
What would be the benefit?

**Comment by nikolay** [comment]
That you don't need to install Ruby. Well, there's the [Traveling Ruby](https://phusion.github.io/traveling-ruby/) project, but a Go binary would be much smaller. Pretty much the entire Kubernetes ecosystem is focused on Go.

**Comment by kke** [comment]
Standalone binaries for `pharos` are available. 

Traveling Ruby only has Ruby 2.2 support. 

Btw, kubectl binary is about 52 megabytes, pharos binary is only about 15 megabytes.
