### ISSUE TITLE
DigitalOcean example not working

### ISSUE THREAD

**Issue by nikolay** [kontena/pharos-cluster#633]
I use your example "as is" and then I get this error:
```
RuntimeError : Overlapping host routes for .network.pod_network_cidr=10.32.0.0/12: #<Pharos::Configuration::Host::Route:0x00007fa0a29e3820>
```

**Comment by jakolehm** [comment]
Should work now.

**Comment by nvg58** [comment]
Same here. I got this error: 
```ERROR: Clamp::ExecutionError : RuntimeError : Overlapping host routes for .network.pod_network_cidr=10.32.0.0/12: #<Pharos::Configuration::Host::Route:0x00007faf67a579b8>```

**Comment by fmoessle** [comment]
Trying to set up with upcloud:

`#<Thread:0x00007fc0350d6f90@/__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/pharos-cluster-2.1.3/lib/pharos/phase_manager.rb:32 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	4: from /__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/pharos-cluster-2.1.3/lib/pharos/phase_manager.rb:33:in `block (2 levels) in run_parallel'
	3: from /__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/pharos-cluster-2.1.3/lib/pharos/phase_manager.rb:52:in `yield_phase_with_retry'
	2: from /__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/pharos-cluster-2.1.3/lib/pharos/phase_manager.rb:88:in `block in apply'
	1: from /__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/pharos-cluster-2.1.3/lib/pharos/phases/validate_host.rb:18:in `call'
/__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/pharos-cluster-2.1.3/lib/pharos/phases/validate_host.rb:70:in `validate_routes': Overlapping host routes for .network.pod_network_cidr=10.32.0.0/12: #<Pharos::Configuration::Host::Route:0x00007fc03495bce8> (RuntimeError)
ERROR: RuntimeError : Overlapping host routes for .network.pod_network_cidr=10.32.0.0/12: #<Pharos::Configuration::Host::Route:0x00007fc03495bce8>`

**Comment by jakolehm** [comment]
@fmoessle @nvg58 could you paste `network` section of the `cluster.yml`?

**Comment by fmoessle** [comment]
It used the one from [here](https://www.kontena.io/pharos#get-started)

```javascript
hosts:
  - address: "XX.XXX.XX.XX"
    role: master
  - address: "XX.XXX.XX.XX"
    role: worker
network:
  provider: weave
addons:
  ingress-nginx:
     enabled: true
```

**Comment by fmoessle** [comment]
@jakolehm this worked! thank you 🙏
