### ISSUE TITLE
Inconsistent relative path referencing for different commands

### ISSUE THREAD

**Issue by kdomanski** [kontena/pharos-cluster#663]
https://github.com/kontena/pharos-cluster/blob/f969e7b54dec51fa5cd44904ab402417ab30ec0b/lib/pharos/up_command.rb#L41-L45

The snippet above changes the working directory in the `up` command, and that command only. This breaks the ability to specify an SSH key as a relative path, while working in a directory different than the config directory.

### Example:
Working directory is `/test` and `ssh_key_path = "../machine-key"`

 - `pharos-cluster up -y -c "aws/cfg.yaml"` expects the key to be located at `/test/machine-key`
 - `pharos-cluster kubeconfig -y -c "aws/cfg.yaml"` expects the key to be located at `/machine-key`

All versions since `v0.6.0` are affected.

**Comment by jnummelin** [comment]
`reset` command changes the working dir the same way, but as you found out `kubeconfig` command does not.
