### ISSUE TITLE
License assign sub-command

### ISSUE THREAD

**Issue by jakolehm** [kontena/pharos-cluster#667]
Should exchange a valid license key to a subscription token and store it to `pharos-license` secret in `kube-system` namespace. 

This replaces `license-manager` addon functionality.

**Comment by kke** [comment]
How to update the secret?

- [X] A: use `-c cluster.yml` + ssh to retrieve kubeconfig and use it to configure `k8s-client` 
- [ ] B: use `-c cluster.yml` + ssh + remote `kubectl`
- [ ] C: parse `ENV['KUBECONFIG']` using `Pharos::Kube::Config` and use the resulting config and the current context in it to configure `k8s-client`

I have a working implementation of option A currently but as it's already using ssh and #668 will also rely on running the remote kubectl, maybe that should be used here too.

**Comment by kke** [comment]
Switched implementation to option `B`.
