### ISSUE TITLE
Possibility to reset only subset of hosts

### ISSUE THREAD

**Issue by jakolehm** [kontena/pharos-cluster#668]

**Comment by kke** [comment]
Allow resetting the last remaining master? Etcd hosts? Should it say something to master when resetting a worker node?

**Comment by jakolehm** [comment]
> Allow resetting the last remaining master when there are workers?

Probably should warn & confirm.

> Should it say something to master when resetting a worker node?

Would be nice if it could (optionally?) first drain a worker node and after reset remove it from the api. @jnummelin WDYT?

**Comment by kke** [comment]
Drain practically requires `kubectl`

**Comment by jakolehm** [comment]
> Drain practically requires kubectl

Yes, but we have it in master hosts.

**Comment by jnummelin** [comment]
Yes, if resetting a node or subset or those, drain would be good.

**Comment by kke** [comment]
Waiting for the #581 so the host filtering can be borrowed from there
