### ISSUE TITLE
kontena-lens: redis should use persistent volume if available

### ISSUE THREAD

**Issue by jakolehm** [kontena/pharos-cluster#730]

**Comment by nevalla** [comment]
In what order plugins are deployed? Thinking could addon just check if default storage exists. If Lens is deployed before the storage plugin, there might not be storage in place yet. One option is to put this behind the configuration option and rely on that there will be storage at some point.

**Comment by jnummelin** [comment]
> Thinking could addon just check if default storage exists

List all `StorageClass`es and see if any of those have the default flag on

But yeah, maybe safest to put a `storage-class` or such option for this.
