### ISSUE TITLE
Validate localhost address

### ISSUE THREAD

**Issue by saeidakbari** [kontena/pharos-cluster#777]
When i try to init a cluster pharos through this error:
`Pharos::InvalidHostError : Localhost ip does not look right: 0.056/0.056`
But when i run this command manually it's correct and return `127.0.0.1`
`ping -c 1 localhost | grep -Eo -m 1 '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}';`

i think it might be a bug

**Comment by a13x212** [comment]
I have the same issue. My host doesn't return 127.0.0.1 though. 

Looks like an issue with ipv6. 

root@kub-node-01:~# ping -c 1 localhost
PING localhost(localhost (::1)) 56 data bytes
64 bytes from localhost (::1): icmp_seq=1 ttl=64 time=0.039 ms

vs 

root@kub-node-01:~# ping -4 -c 1 localhost
PING localhost (127.0.0.1) 56(84) bytes of data.
64 bytes from localhost (127.0.0.1): icmp_seq=1 ttl=64 time=0.022 ms

--- localhost ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.022/0.022/0.022/0.000 ms

**Comment by jakolehm** [comment]
Could you check if the following snippet gives a correct output:
```
getent ahostsv4 localhost | grep STREAM | head -n 1 | cut -d ' ' -f1
```

**Comment by kke** [comment]
I wonder if `grep` is an alias when you run it manually and pharos runs it unaliased and gets something else when it runs it through env. I think I've seen something like `alias grep=fgrep` on some systems.

Can you check what `alias grep` says or if `ping -c 1 localhost | env grep -Eo -m 1 '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}'` gives this strange `0.056/0.056`?

**Comment by saeidakbari** [comment]
I solved it.
The problem is because of IPv6 settings in `hosts` file.
i configured it like this and it's work fine.
```
127.0.0.1	localhost
# The following lines are desirable for IPv6 capable hosts
::1 ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
ff02::3 ip6-allhosts
```

But a new problem happened.
Setup stuck in kubelet configuration.
The docker logs of `etcd` container says that `cannot connect to localhost, transport is closing`
any idea?
