### ISSUE TITLE
CentOS update docker

### ISSUE THREAD

**Issue by Timer** [kontena/pharos-cluster#782]
It appears ubuntu/friends are on a newer version of Docker than EL7 variants:

https://github.com/kontena/pharos-cluster/blob/master/lib/pharos/host/ubuntu/ubuntu_xenial.rb#L10
https://github.com/kontena/pharos-cluster/blob/master/lib/pharos/host/el7/centos7.rb#L10

It'd be great to upgrade CentOS to Docker >=17 (18 would be even better).

**Comment by Timer** [comment]
Note: the primary motivation behind this is that running a CI system on Kubernetes will reach-through to host docker and build images. A worthy mention is the lack of multi-stage builds.

**Comment by jakolehm** [comment]
One good option for CI is the famous docker-in-docker.

**Comment by Timer** [comment]
Haha, I'll give it a whirl but this would probably be nice nevertheless.

**Comment by Timer** [comment]
Went with DinD, I guess this can be closed.
