### ISSUE TITLE
ExecutionError : SocketError : getaddrinfo: Name or service not known

### ISSUE THREAD

**Issue by ammarqq** [kontena/pharos-cluster#811]
When I try to run command : pharos up -c cluster.yml

it gave me this error : 

==> KONTENA PHAROS v2.0.2-rc.1 (Kubernetes v1.11.4)
==> Reading instructions ...
==> Sharpening tools ...
==> Check for Pharos upgrade @ localhost
    [localhost] Checking for a new version ...
==> Gather host facts @ 10.200.224.1 10.200.224.9  10.200.224.8 10.200.247.255 10.200.224.2 10.200.224.3 10.200.224.4
ERROR: Clamp::ExecutionError : SocketError : getaddrinfo: Name or service not known

I tried it on different versions 2.0.1 and 2.0.0 I got the same issue .

I'm sure from the ssh key I'm trying to install kubernetes on baremetal servers.

KR
Amm

**Comment by kke** [comment]
Could you run with `-d` option and get a full backtrace?

**Comment by kke** [comment]
You may need to set [`api: endpoint:`](https://pharos.sh/docs/configuration.html#api) in cluster.yml

**Comment by ammarqq** [comment]
hello kke,
I run the command and the output as below : 
pharos up  -c cluster.yml -d
==> KONTENA PHAROS v2.0.2-rc.1 (Kubernetes v1.11.4)
==> Reading instructions ...
==> Sharpening tools ...
==> Check for Pharos upgrade @ localhost
    [localhost] Checking for a new version ...
    [localhost] Upgrade check encountered an error: SSL_connect returned=1 errno=0 state=error: certificate verify failed (OpenSSL::SSL::SSLError) Unable to verify certificate. This may be an issue with the remote host or with Excon. Excon has certificates bundled, but these can be customized:

            `Excon.defaults[:ssl_ca_path] = path_to_certs`
            `ENV['SSL_CERT_DIR'] = path_to_certs`
            `Excon.defaults[:ssl_ca_file] = path_to_file`
            `ENV['SSL_CERT_FILE'] = path_to_file`
            `Excon.defaults[:ssl_verify_callback] = callback`
                (see OpenSSL::SSL::SSLContext#verify_callback)
or:
            `Excon.defaults[:ssl_verify_peer] = false` (less secure).
 : SSL_connect returned=1 errno=0 state=error: certificate verify failed (OpenSSL::SSL::SSLError) Unable to verify certificate. This may be an issue with the remote host or with Excon. Excon has certificates bundled, but these can be customized:

            `Excon.defaults[:ssl_ca_path] = path_to_certs`
            `ENV['SSL_CERT_DIR'] = path_to_certs`
            `Excon.defaults[:ssl_ca_file] = path_to_file`
            `ENV['SSL_CERT_FILE'] = path_to_file`
            `Excon.defaults[:ssl_verify_callback] = callback`
                (see OpenSSL::SSL::SSLContext#verify_callback)
or:
            `Excon.defaults[:ssl_verify_peer] = false` (less secure).

    Completed Check for Pharos upgrade @ localhost in 0.324s
==> Gather host facts @ 10.200.224.1 10.200.224.9  10.200.224.8 10.200.247.255 10.200.224.2 10.200.224.3 10.200.224.4
/__enclose_io_memfs__/lib/ruby/2.4.0/socket.rb:227:in `getaddrinfo': getaddrinfo: Name or service not known (SocketError)
	from /__enclose_io_memfs__/lib/ruby/2.4.0/socket.rb:227:in `foreach'
	from /__enclose_io_memfs__/lib/ruby/2.4.0/socket.rb:617:in `tcp'
	from /__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/net-ssh-5.0.2/lib/net/ssh/transport/session.rb:73:in `initialize'
	from /__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/net-ssh-5.0.2/lib/net/ssh.rb:242:in `new'
	from /__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/net-ssh-5.0.2/lib/net/ssh.rb:242:in `start'
	from /__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/pharos-cluster-2.0.2.rc.1/lib/pharos/ssh/client.rb:47:in `connect'
	from /__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/pharos-cluster-2.0.2.rc.1/lib/pharos/ssh/manager.rb:24:in `tap'
	from /__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/pharos-cluster-2.0.2.rc.1/lib/pharos/ssh/manager.rb:24:in `client_for'
	from /__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/pharos-cluster-2.0.2.rc.1/lib/pharos/phase_manager.rb:81:in `prepare_phase'
	from /__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/pharos-cluster-2.0.2.rc.1/lib/pharos/phase_manager.rb:87:in `block in apply'
	from /__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/pharos-cluster-2.0.2.rc.1/lib/pharos/phase_manager.rb:87:in `map'
	from /__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/pharos-cluster-2.0.2.rc.1/lib/pharos/phase_manager.rb:87:in `apply'
	from /__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/pharos-cluster-2.0.2.rc.1/lib/pharos/cluster_manager.rb:171:in `apply_phase'
	from /__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/pharos-cluster-2.0.2.rc.1/lib/pharos/cluster_manager.rb:66:in `gather_facts'
	from /__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/pharos-cluster-2.0.2.rc.1/lib/pharos/cluster_manager.rb:73:in `validate'
	from /__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/pharos-cluster-2.0.2.rc.1/lib/pharos/up_command.rb:34:in `configure'
	from /__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/pharos-cluster-2.0.2.rc.1/lib/pharos/up_command.rb:20:in `block in execute'
	from /__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/pharos-cluster-2.0.2.rc.1/lib/pharos/up_command.rb:19:in `chdir'
	from /__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/pharos-cluster-2.0.2.rc.1/lib/pharos/up_command.rb:19:in `execute'
	from /__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/clamp-1.2.1/lib/clamp/command.rb:63:in `run'
	from /__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/pharos-cluster-2.0.2.rc.1/lib/pharos/command.rb:16:in `run'
	from /__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/clamp-1.2.1/lib/clamp/subcommand/execution.rb:11:in `execute'
	from /__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/clamp-1.2.1/lib/clamp/command.rb:63:in `run'
	from /__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/pharos-cluster-2.0.2.rc.1/lib/pharos/command.rb:16:in `run'
	from /__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/clamp-1.2.1/lib/clamp/command.rb:132:in `run'
	from /__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/pharos-cluster-2.0.2.rc.1/bin/pharos-cluster:13:in `<top (required)>'
	from /__enclose_io_memfs__/lib/ruby/gems/2.4.0/bin/pharos-cluster:23:in `load'
	from /__enclose_io_memfs__/lib/ruby/gems/2.4.0/bin/pharos-cluster:23:in `<main>'

**Comment by kke** [comment]
So, looks like the pharos update check fails. The machine you're running pharos on does not have access to public internet?

You may be able to skip that by setting `PHAROS_UPGRADE_CHECK_URL` environment variable to for example `http://127.0.0.1' before running pharos, so:

```
PHAROS_UPGRADE_CHECK_URL=http://127.0.0.1 pharos up -c cluster.yml
````

**Comment by ammarqq** [comment]
thanks kke for your help  I checked the internet and the latest command as below : 
PHAROS_UPGRADE_CHECK_URL=http://127.0.0.1 pharos up -c cluster.yml
==> KONTENA PHAROS v2.0.2-rc.1 (Kubernetes v1.11.4)
==> Reading instructions ...
==> Sharpening tools ...
==> Check for Pharos upgrade @ localhost
    [localhost] Checking for a new version ...
==> Gather host facts @ 10.200.224.1 10.200.224.9  10.200.224.8 10.200.247.255 10.200.224.2 10.200.224.3 10.200.224.4
ERROR: Clamp::ExecutionError : SocketError : getaddrinfo: Name or service not known
root@ktest1:~# ping google.com
PING google.com (172.217.18.46) 56(84) bytes of data.
64 bytes from ham02s12-in-f46.1e100.net (172.217.18.46): icmp_seq=1 ttl=49 time=76.8 ms
64 bytes from ham02s12-in-f46.1e100.net (172.217.18.46): icmp_seq=2 ttl=49 time=76.9 ms
64 bytes from ham02s12-in-f46.1e100.net (172.217.18.46): icmp_seq=3 ttl=49 time=76.6 ms
64 bytes from ham02s12-in-f46.1e100.net (172.217.18.46): icmp_seq=4 ttl=49 time=76.7 ms
64 bytes from ham02s12-in-f46.1e100.net (172.217.18.46): icmp_seq=5 ttl=49 time=76.6 ms
^C
--- google.com ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4006ms
rtt min/avg/max/mdev = 76.624/76.760/76.971/0.331 ms

still the same issue .
thanks

**Comment by kke** [comment]
The upgrade check bug is actually unrelated, but a good thing it was found.

Can you connect to those `10.*` ip's from the machine you're running pharos on?

**Comment by kke** [comment]
Ah, there seems to be a space in front of one of the IP's:

```
  10.200.224.8
```

it's trying to do a DNS resolve for that.

**Comment by kke** [comment]
Or after the previous one that ends in 9

**Comment by ammarqq** [comment]
you are totally right , many thanks it worked ,I reviewed the file 100 time and i didn't notice the space :+1: 

many thanks kke.
