### ISSUE TITLE
Comparing kube-apiserver version fails when tried to upgrade pharos cluster to 2.1.0

### ISSUE THREAD

**Issue by nevalla** [kontena/pharos-cluster#848]
Comparing kube-apiserver version fails when tried to upgrade pharos cluster to 2.1.0-dev:
```
NoMethodError: undefined method `[]' for nil:NilClass
  /Users/lauri/Projects/pharos-cluster/lib/pharos/phases/upgrade_master.rb:17:in `upgrade?'
```

It seems that `upgrade?` method tries to search `kube-apiserver:v(.+)` from `kube-apiserver.yml`, but the format has changed to `image: registry.pharos.sh/kontenapharos/kube-apiserver-amd64:v1.11.4`

**Comment by jakolehm** [comment]
Actually 2.0.x has `kube-apiserver-amd64:v1.x.x` and 2.1.x has `kube-apiserver:v1.x.x`.
