### ISSUE TITLE
Registering new node to cluster

### ISSUE THREAD

**Issue by jakubknejzlik** [kontena/pharos-cluster#901]
**What would you like to be added**:
Documentation how to add new node to cluster. From my understanding I need to update the list of worker/master nodes and run pharos-cluster up. This means that all nodes are update one by one. Is there a way how to do registration of node without running the whole cluster update?

**Why is this needed**:
Adding node (especially worker) should be easy and quick job, in my situation when I run Pharos-cluster up all nodes are one by one “paused”, updated and then “resumed”. This means that all pods are moved to separate nodes and this process could be slow in some cases.

**Comment by jakolehm** [comment]
> Adding node (especially worker) should be easy and quick job, in my situation when I run Pharos-cluster up all nodes are one by one “paused”, updated and then “resumed”. This means that all pods are moved to separate nodes and this process could be slow in some cases.

Pharos should pause/resume (drain/uncordon) only when container runtime (or similar critical component) is upgraded. Which host OS are you using?

**Comment by jnummelin** [comment]
@jakubknejzlik  The procedure is documented at https://pharos.sh/docs/deploy.html#adding-worker-nodes

As @jakolehm mentioned, if only adding a node and no other changes (config, versions etc.) the node drain/un-cordon should NOT happen. If it does, it's pretty much a bug.

**Comment by jnummelin** [comment]
@jakubknejzlik Please re-open if you still see the drain & un-cordoning happening during worker add if no runtime version etc. changes.

**Comment by jakubknejzlik** [comment]
Sorry guys for not replying. I’ve recently added new nodes and it went well withou any unnecessary draining. Thank you!
